export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES_BY_CONTINENT: Record<string, Country[]> = {
  'América': [
    { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
    { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
    { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
    { code: 'CA', name: 'Canadá', flag: '🇨🇦' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
    { code: 'DO', name: 'República Dominicana', flag: '🇩🇴' },
    { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
    { code: 'HT', name: 'Haití', flag: '🇭🇹' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
    { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
    { code: 'MX', name: 'México', flag: '🇲🇽' },
    { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
    { code: 'PA', name: 'Panamá', flag: '🇵🇦' },
    { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
    { code: 'PE', name: 'Perú', flag: '🇵🇪' },
    { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
    { code: 'TT', name: 'Trinidad y Tobago', flag: '🇹🇹' },
    { code: 'US', name: 'Estados Unidos', flag: '🇺🇸' },
    { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
    { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
    { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
    { code: 'SR', name: 'Surinam', flag: '🇸🇷' },
  ],
  'Europa': [
    { code: 'AL', name: 'Albania', flag: '🇦🇱' },
    { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹' },
    { code: 'BY', name: 'Bielorrusia', flag: '🇧🇾' },
    { code: 'BE', name: 'Bélgica', flag: '🇧🇪' },
    { code: 'BA', name: 'Bosnia y Herzegovina', flag: '🇧🇦' },
    { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
    { code: 'HR', name: 'Croacia', flag: '🇭🇷' },
    { code: 'CY', name: 'Chipre', flag: '🇨🇾' },
    { code: 'CZ', name: 'República Checa', flag: '🇨🇿' },
    { code: 'DK', name: 'Dinamarca', flag: '🇩🇰' },
    { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
    { code: 'FI', name: 'Finlandia', flag: '🇫🇮' },
    { code: 'FR', name: 'Francia', flag: '🇫🇷' },
    { code: 'DE', name: 'Alemania', flag: '🇩🇪' },
    { code: 'GR', name: 'Grecia', flag: '🇬🇷' },
    { code: 'HU', name: 'Hungría', flag: '🇭🇺' },
    { code: 'IS', name: 'Islandia', flag: '🇮🇸' },
    { code: 'IE', name: 'Irlanda', flag: '🇮🇪' },
    { code: 'IT', name: 'Italia', flag: '🇮🇹' },
    { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
    { code: 'LV', name: 'Letonia', flag: '🇱🇻' },
    { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
    { code: 'LT', name: 'Lituania', flag: '🇱🇹' },
    { code: 'LU', name: 'Luxemburgo', flag: '🇱🇺' },
    { code: 'MT', name: 'Malta', flag: '🇲🇹' },
    { code: 'MD', name: 'Moldavia', flag: '🇲🇩' },
    { code: 'MC', name: 'Mónaco', flag: '🇲🇨' },
    { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
    { code: 'NL', name: 'Países Bajos', flag: '🇳🇱' },
    { code: 'MK', name: 'Macedonia del Norte', flag: '🇲🇰' },
    { code: 'NO', name: 'Noruega', flag: '🇳🇴' },
    { code: 'PL', name: 'Polonia', flag: '🇵🇱' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
    { code: 'RO', name: 'Rumanía', flag: '🇷🇴' },
    { code: 'RU', name: 'Rusia', flag: '🇷🇺' },
    { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
    { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
    { code: 'SK', name: 'Eslovaquia', flag: '🇸🇰' },
    { code: 'SI', name: 'Eslovenia', flag: '🇸🇮' },
    { code: 'ES', name: 'España', flag: '🇪🇸' },
    { code: 'SE', name: 'Suecia', flag: '🇸🇪' },
    { code: 'CH', name: 'Suiza', flag: '🇨🇭' },
    { code: 'UA', name: 'Ucrania', flag: '🇺🇦' },
    { code: 'GB', name: 'Reino Unido', flag: '🇬🇧' },
    { code: 'VA', name: 'Ciudad del Vaticano', flag: '🇻🇦' },
  ],
  'Asia': [
    { code: 'AF', name: 'Afganistán', flag: '🇦🇫' },
    { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
    { code: 'AZ', name: 'Azerbaiyán', flag: '🇦🇿' },
    { code: 'BH', name: 'Baréin', flag: '🇧🇭' },
    { code: 'BD', name: 'Bangladés', flag: '🇧🇩' },
    { code: 'BT', name: 'Bután', flag: '🇧🇹' },
    { code: 'BN', name: 'Brunéi', flag: '🇧🇳' },
    { code: 'KH', name: 'Camboya', flag: '🇰🇭' },
    { code: 'CN', name: 'China', flag: '🇨🇳' },
    { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
    { code: 'IN', name: 'India', flag: '🇮🇳' },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
    { code: 'IR', name: 'Irán', flag: '🇮🇷' },
    { code: 'IQ', name: 'Irak', flag: '🇮🇶' },
    { code: 'IL', name: 'Israel', flag: '🇮🇱' },
    { code: 'JP', name: 'Japón', flag: '🇯🇵' },
    { code: 'JO', name: 'Jordania', flag: '🇯🇴' },
    { code: 'KZ', name: 'Kazajistán', flag: '🇰🇿' },
    { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
    { code: 'KG', name: 'Kirguistán', flag: '🇰🇬' },
    { code: 'LA', name: 'Laos', flag: '🇱🇦' },
    { code: 'LB', name: 'Líbano', flag: '🇱🇧' },
    { code: 'MY', name: 'Malasia', flag: '🇲🇾' },
    { code: 'MV', name: 'Maldivas', flag: '🇲🇻' },
    { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
    { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
    { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
    { code: 'KP', name: 'Corea del Norte', flag: '🇰🇵' },
    { code: 'OM', name: 'Omán', flag: '🇴🇲' },
    { code: 'PK', name: 'Pakistán', flag: '🇵🇰' },
    { code: 'PH', name: 'Filipinas', flag: '🇵🇭' },
    { code: 'QA', name: 'Catar', flag: '🇶🇦' },
    { code: 'SA', name: 'Arabia Saudita', flag: '🇸🇦' },
    { code: 'SG', name: 'Singapur', flag: '🇸🇬' },
    { code: 'KR', name: 'Corea del Sur', flag: '🇰🇷' },
    { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
    { code: 'SY', name: 'Siria', flag: '🇸🇾' },
    { code: 'TW', name: 'Taiwán', flag: '🇹🇼' },
    { code: 'TJ', name: 'Tayikistán', flag: '🇹🇯' },
    { code: 'TH', name: 'Tailandia', flag: '🇹🇭' },
    { code: 'TL', name: 'Timor Oriental', flag: '🇹🇱' },
    { code: 'TR', name: 'Turquía', flag: '🇹🇷' },
    { code: 'TM', name: 'Turkmenistán', flag: '🇹🇲' },
    { code: 'AE', name: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
    { code: 'UZ', name: 'Uzbekistán', flag: '🇺🇿' },
    { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
    { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
    { code: 'PS', name: 'Palestina', flag: '🇵🇸' },
  ],
  'África': [
    { code: 'DZ', name: 'Argelia', flag: '🇩🇿' },
    { code: 'AO', name: 'Angola', flag: '🇦🇴' },
    { code: 'BJ', name: 'Benín', flag: '🇧🇯' },
    { code: 'BW', name: 'Botsuana', flag: '🇧🇼' },
    { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
    { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
    { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
    { code: 'CM', name: 'Camerún', flag: '🇨🇲' },
    { code: 'CF', name: 'República Centroafricana', flag: '🇨🇫' },
    { code: 'TD', name: 'Chad', flag: '🇹🇩' },
    { code: 'KM', name: 'Comoras', flag: '🇰🇲' },
    { code: 'CG', name: 'Congo', flag: '🇨🇬' },
    { code: 'CD', name: 'Rep. Dem. del Congo', flag: '🇨🇩' },
    { code: 'CI', name: 'Costa de Marfil', flag: '🇨🇮' },
    { code: 'DJ', name: 'Yibuti', flag: '🇩🇯' },
    { code: 'EG', name: 'Egipto', flag: '🇪🇬' },
    { code: 'GQ', name: 'Guinea Ecuatorial', flag: '🇬🇶' },
    { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
    { code: 'ET', name: 'Etiopía', flag: '🇪🇹' },
    { code: 'GA', name: 'Gabón', flag: '🇬🇦' },
    { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
    { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
    { code: 'GN', name: 'Guinea', flag: '🇬🇳' },
    { code: 'GW', name: 'Guinea-Bisáu', flag: '🇬🇼' },
    { code: 'KE', name: 'Kenia', flag: '🇰🇪' },
    { code: 'LS', name: 'Lesoto', flag: '🇱🇸' },
    { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
    { code: 'LY', name: 'Libia', flag: '🇱🇾' },
    { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
    { code: 'MW', name: 'Malaui', flag: '🇲🇼' },
    { code: 'ML', name: 'Malí', flag: '🇲🇱' },
    { code: 'MR', name: 'Mauritania', flag: '🇲🇷' },
    { code: 'MU', name: 'Mauricio', flag: '🇲🇺' },
    { code: 'MA', name: 'Marruecos', flag: '🇲🇦' },
    { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
    { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
    { code: 'NE', name: 'Níger', flag: '🇳🇪' },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
    { code: 'RW', name: 'Ruanda', flag: '🇷🇼' },
    { code: 'ST', name: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
    { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
    { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
    { code: 'SL', name: 'Sierra Leona', flag: '🇸🇱' },
    { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
    { code: 'ZA', name: 'Sudáfrica', flag: '🇿🇦' },
    { code: 'SS', name: 'Sudán del Sur', flag: '🇸🇸' },
    { code: 'SD', name: 'Sudán', flag: '🇸🇩' },
    { code: 'SZ', name: 'Suazilandia', flag: '🇸🇿' },
    { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
    { code: 'TG', name: 'Togo', flag: '🇹🇬' },
    { code: 'TN', name: 'Túnez', flag: '🇹🇳' },
    { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
    { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
    { code: 'ZW', name: 'Zimbabue', flag: '🇿🇼' },
  ],
  'Oceanía': [
    { code: 'AU', name: 'Australia', flag: '🇦🇺' },
    { code: 'FJ', name: 'Fiyi', flag: '🇫🇯' },
    { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
    { code: 'MH', name: 'Islas Marshall', flag: '🇲🇭' },
    { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
    { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
    { code: 'NZ', name: 'Nueva Zelanda', flag: '🇳🇿' },
    { code: 'PW', name: 'Palaos', flag: '🇵🇼' },
    { code: 'PG', name: 'Papúa Nueva Guinea', flag: '🇵🇬' },
    { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
    { code: 'SB', name: 'Islas Salomón', flag: '🇸🇧' },
    { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
    { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
    { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  ],
};

export const COUNTRIES = Object.values(COUNTRIES_BY_CONTINENT).flat();
export const countryByCode = Object.fromEntries(COUNTRIES.map((c) => [c.code, c]));
